export const PERMISSIONS = {
  // User Management
  CREATE_USER: "CREATE_USER",
  VIEW_USERS: "VIEW_USERS",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",
  IMPERSONATE_USER: "IMPERSONATE_USER", // Future Phase

  // CRM Leads
  VIEW_LEADS: "VIEW_LEADS",
  EDIT_LEAD: "EDIT_LEAD",
  ASSIGN_LEADS: "ASSIGN_LEADS",
  EXPORT_LEADS: "EXPORT_LEADS",

  // System
  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",
  MANAGE_SETTINGS: "MANAGE_SETTINGS",
} as const;

export type Permission = keyof typeof PERMISSIONS;
